import type { ApprovalRecord } from './approval-gate'
import type { AuditDirectory } from './durable-audit-store'

export type LoadedApproval = Readonly<{ record: ApprovalRecord; snapshot: string }>
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
const HEX=/^[a-f0-9]{64}$/
function validate(value: unknown): ApprovalRecord { const r=value as Partial<ApprovalRecord>; if(!r||typeof r!=='object'||r.schemaVersion!==1||r.status!=='APPROVED'||r.statementVersion!==1||typeof r.assetId!=='string'||!UUID.test(r.assetId)||!Number.isInteger(r.revision)||r.revision!<1||typeof r.approvedAt!=='string'||typeof r.rulesetId!=='string'||typeof r.rulesetVersion!=='string'||typeof r.submissionChecksum!=='string'||!HEX.test(r.submissionChecksum)||typeof r.metadataChecksum!=='string'||!HEX.test(r.metadataChecksum)||typeof r.auditChecksum!=='string'||!HEX.test(r.auditChecksum)) throw Error('approval record is invalid'); return value as ApprovalRecord }
async function read(d:AuditDirectory,n:string){try{return await (await d.getFileHandle(n,{create:false})).getFile().then(f=>f.text())}catch(e){if(e instanceof DOMException&&e.name==='NotFoundError')return undefined;throw e}}
export async function loadApproval(d:AuditDirectory,assetId:string,revision:number):Promise<LoadedApproval|undefined>{if(!UUID.test(assetId)||!Number.isInteger(revision)||revision<1)throw Error('approval identity is invalid');const reports=await d.getDirectoryHandle('reports',{create:false});const dir=await reports.getDirectoryHandle('approvals',{create:false});const snapshot=await read(dir,`${assetId}-r${revision}.json`);if(snapshot===undefined)return undefined;try{return {record:validate(JSON.parse(snapshot)),snapshot}}catch{throw Error('approval record is invalid')}}
export async function saveApproval(d:AuditDirectory,record:ApprovalRecord,existingSnapshot?:string):Promise<LoadedApproval>{const valid=validate(record);const reports=await d.getDirectoryHandle('reports',{create:false});const dir=await reports.getDirectoryHandle('approvals',{create:true});const name=`${valid.assetId}-r${valid.revision}.json`;const current=await read(dir,name);if(current!==existingSnapshot)throw Error('approval changed externally; reload before saving');const w=await (await dir.getFileHandle(name,{create:true})).createWritable();const snapshot=JSON.stringify(valid,null,2)+'\n';await w.write(snapshot);await w.close();return {record:valid,snapshot}}
