import { describe, expect, it } from 'vitest'
import { resolveApprovalSubmission } from './approval-submission'

/* eslint-disable @typescript-eslint/require-await */

const id = '123e4567-e89b-12d3-a456-426614174000'
const revision = { revision: 2, generation_format: 'jpeg' as const, working_format: 'jpeg' as const, master_format: 'jpeg' as const, submission_format: 'jpeg' as const, relative_path: 'revisions/123/2/master.jpeg' }
const validJpeg = new Uint8Array([0xff, 0xd8, 0xff, 0xd9])
const validJpegChecksum = '32461d5bd1773012acef0ba15636752949bd7c2ce50f9172159d9f56cf0dd9af'
const manifest = { schema_version: 1 as const, project_id: id, project_name: 'Test', assets: [{ asset_id: id, content_type: 'photo' as const, creation_method: 'camera' as const, revisions: [revision] }] }
type Node = { files: Map<string, File>; dirs: Map<string, Node> }
const node = (): Node => ({ files: new Map(), dirs: new Map() })
const directory = (root: Node) => ({ getDirectoryHandle: async (name: string) => { const found = root.dirs.get(name); if (!found) throw new DOMException('missing', 'NotFoundError'); return directory(found) }, getFileHandle: async (name: string) => { const file = root.files.get(name); if (!file) throw new DOMException('missing', 'NotFoundError'); return { getFile: async () => file } } }) as never
const metadata = JSON.stringify({ schemaVersion: 1, title: 'Bird', keywords: ['bird', 'sky', 'sea', 'light', 'nature'], category: 'animals', contentType: 'photo', creationMethod: 'camera', generatedWithAi: false, aiDisclosure: '', releaseStatus: 'not_required' })
const manifestWithUuidPath = { schema_version: 1 as const, project_id: id, project_name: 'Test', assets: [{ asset_id: id, content_type: 'photo' as const, creation_method: 'camera' as const, revisions: [{ revision: 2, generation_format: 'jpeg' as const, working_format: 'jpeg' as const, master_format: 'jpeg' as const, submission_format: 'jpeg' as const, relative_path: `revisions/${id}/2/master.jpeg` }] }] }
describe('approval submission resolver', () => {
  it('reads nested revision bytes and computes actual checksum', async () => { const root = node(); root.files.set('gandiwa-project.json', new File(['manifest'], 'gandiwa-project.json')); const bytes = validJpeg; const revisions = node(); const asset = node(); const number = node(); number.files.set('master.jpeg', new File([bytes], 'master.jpeg', { type: 'image/jpeg' })); number.files.set('preparation.json', new File([JSON.stringify({ submission_checksum: validJpegChecksum })], 'preparation.json')); asset.dirs.set('2', number); revisions.dirs.set('123', asset); root.dirs.set('revisions', revisions); const metadataDirectory = node(); metadataDirectory.files.set(`${id}.json`, new File([metadata], `${id}.json`)); root.dirs.set('metadata', metadataDirectory); const result = await resolveApprovalSubmission({ directory: directory(root), manifest, manifestSnapshot: 'manifest', assetId: id, revision: 2 }); expect(result.path).toBe('revisions/123/2/master.jpeg'); expect(result.submissionChecksum).toHaveLength(64); expect(result.file.size).toBe(4) })
  it('rejects traversal paths', async () => { const root = node(); root.files.set('gandiwa-project.json', new File(['manifest'], 'gandiwa-project.json')); const badManifest = { schema_version: 1 as const, project_id: id, project_name: 'Test', assets: [{ asset_id: id, content_type: 'photo' as const, creation_method: 'camera' as const, revisions: [{ revision: 2, generation_format: 'jpeg' as const, working_format: 'jpeg' as const, master_format: 'jpeg' as const, submission_format: 'jpeg' as const, relative_path: 'revisions/../secret.jpeg' }] }] }; await expect(resolveApprovalSubmission({ directory: directory(root), manifest: badManifest, manifestSnapshot: 'manifest', assetId: id, revision: 2 })).rejects.toThrow(/path is invalid|normalized relative path/) })
  it('rejects a prepared submission whose preparation checksum disagrees with actual bytes', async () => { const root = node(); root.files.set('gandiwa-project.json', new File(['manifest'], 'gandiwa-project.json')); const bytes = validJpeg; const revisions = node(); const asset = node(); const number = node(); number.files.set('master.jpeg', new File([bytes], 'master.jpeg', { type: 'image/jpeg' })); number.files.set('preparation.json', new File([JSON.stringify({ submission_checksum: 'f'.repeat(64) })], 'preparation.json')); asset.dirs.set('2', number); revisions.dirs.set(id, asset); root.dirs.set('revisions', revisions); const metadataDirectory = node(); metadataDirectory.files.set(`${id}.json`, new File([metadata], `${id}.json`)); root.dirs.set('metadata', metadataDirectory); await expect(resolveApprovalSubmission({ directory: directory(root), manifest: manifestWithUuidPath, manifestSnapshot: 'manifest', assetId: id, revision: 2 })).rejects.toThrow(/preparation checksum/) })
  it('rejects bytes that do not match the declared JPEG format', async () => { const root = node(); root.files.set('gandiwa-project.json', new File(['manifest'], 'gandiwa-project.json')); const bytes = new Uint8Array([0xff, 0xd8, 0xff]); const revisions = node(); const asset = node(); const number = node(); number.files.set('master.jpeg', new File([bytes], 'master.jpeg', { type: 'image/jpeg' })); asset.dirs.set('2', number); revisions.dirs.set(id, asset); root.dirs.set('revisions', revisions); await expect(resolveApprovalSubmission({ directory: directory(root), manifest: manifestWithUuidPath, manifestSnapshot: 'manifest', assetId: id, revision: 2 })).rejects.toThrow(/format/) })
})
