import { ADOBE_STOCK_MVP_RULESET_ID } from '@gandiwa/adobe-rules'
import type { DurableAuditSnapshot } from './approval-gate'

export type AuditFile = { getFile(): Promise<{ text(): Promise<string> }>; createWritable(): Promise<{ write(value: string): Promise<void>; close(): Promise<void> }> }
export type AuditDirectory = { getDirectoryHandle(name: string, options?: { create?: boolean }): Promise<AuditDirectory>; getFileHandle(name: string, options?: { create?: boolean }): Promise<AuditFile> }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
const HEX=/^[a-f0-9]{64}$/
const hash=async(s:string)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('')
export function validateDurableAudit(value: unknown): DurableAuditSnapshot { const a=value as Partial<DurableAuditSnapshot>; if(!a||typeof a!=='object'||a.schemaVersion!==1||typeof a.assetId!=='string'||!UUID.test(a.assetId)||!Number.isInteger(a.revision)||a.revision!<1||typeof a.submissionChecksum!=='string'||!HEX.test(a.submissionChecksum)||typeof a.rulesetId!=='string'||a.rulesetId!==ADOBE_STOCK_MVP_RULESET_ID||typeof a.rulesetVersion!=='string'||a.rulesetVersion!==ADOBE_STOCK_MVP_RULESET_ID||!Array.isArray(a.findings)||typeof a.createdAt!=='string') throw new Error('audit snapshot is invalid'); return value as DurableAuditSnapshot }
async function read(d:AuditDirectory,n:string){try{return await (await d.getFileHandle(n,{create:false})).getFile().then(f=>f.text())}catch(e){if(e instanceof DOMException&&e.name==='NotFoundError')return undefined;throw e}}
export async function loadDurableAudit(d:AuditDirectory,assetId:string,revision:number){if(!UUID.test(assetId)||!Number.isInteger(revision)||revision<1)throw Error('audit identity is invalid');const r=await d.getDirectoryHandle('reports',{create:false});const a=await r.getDirectoryHandle('audits',{create:false});const snapshot=await read(a,`${assetId}-r${revision}.json`);if(snapshot===undefined)return undefined;let parsed:unknown;try{parsed=JSON.parse(snapshot)}catch{throw Error('audit snapshot is invalid')}const audit=validateDurableAudit(parsed);return {audit,snapshot,checksum:await hash(snapshot)}}
export async function saveDurableAudit(input:{directory:AuditDirectory;manifestSnapshot:string;audit:DurableAuditSnapshot;sidecarSnapshot?:string}){const audit=validateDurableAudit(input.audit);const manifest=await read(input.directory,'gandiwa-project.json');if(manifest!==input.manifestSnapshot)throw Error('project manifest changed externally; reload before saving audit');const reports=await input.directory.getDirectoryHandle('reports',{create:false});const dir=await reports.getDirectoryHandle('audits',{create:true});const name=`${audit.assetId}-r${audit.revision}.json`;const current=await read(dir,name);if(current!==input.sidecarSnapshot)throw Error('audit changed externally; reload before saving');const snapshot=JSON.stringify(audit,null,2)+'\n';if(await read(input.directory,'gandiwa-project.json')!==input.manifestSnapshot||await read(dir,name)!==input.sidecarSnapshot)throw Error('audit changed externally; reload before saving');const w=await (await dir.getFileHandle(name,{create:true})).createWritable();await w.write(snapshot);await w.close();return {audit,snapshot,checksum:await hash(snapshot)}}
