(() => {
'use strict';
const API='/api/v1'; const BOOTSTRAP_URL='/api/v1/creative/bootstrap'; const JOBS_URL='/api/v1/creative/jobs'; const RASTER_PREFLIGHT_URL='/api/v1/raster/preflight'; const SVG_PREFLIGHT_URL='/api/v1/svg/preflight'; const KEY='gandiwa.rev3.state.v1';
const $=s=>document.querySelector(s); const by=id=>document.getElementById(id);
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const put=x=>localStorage.setItem(KEY,JSON.stringify({...get(),...x}));
const DB='gandiwa-rev3-handles';
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('handles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error('Local project storage unavailable.'))})}
async function rememberDir(dir){const d=await db();await new Promise((resolve,reject)=>{const r=d.transaction('handles','readwrite').objectStore('handles').put(dir,'active');r.onsuccess=resolve;r.onerror=()=>reject(r.error)});d.close()}
async function recalledDir(){const d=await db();const result=await new Promise((resolve,reject)=>{const r=d.transaction('handles','readonly').objectStore('handles').get('active');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});d.close();return result}
const say=(id,msg,ok=false)=>{const n=by(id);if(n){n.textContent=msg;n.className=`${n.className.split(' ')[0]}${ok?' ok':''}`}};
const text=(r)=>r.text().then(t=>{try{return JSON.parse(t)}catch{return {detail:t}}});
async function csrf(){const r=await fetch(`${API}/auth/csrf`,{credentials:'same-origin'}),b=await text(r);if(!r.ok||!b.csrf_token)throw Error('Token keamanan backend tidak tersedia.');return b.csrf_token}
async function boot(){const r=await fetch(`${API}/creative/bootstrap`,{credentials:'same-origin'});if(!r.ok)throw Error('Sesi backend tidak siap.');}
async function pick(){if(!window.showDirectoryPicker)throw Error('Gunakan Chrome atau Edge untuk folder proyek lokal.');return window.showDirectoryPicker()}
async function readManifest(dir){const f=await dir.getFileHandle('gandiwa-project.json');const raw=await (await f.getFile()).text();return {raw,manifest:JSON.parse(raw)}}
async function write(dir,name,value){const h=await dir.getFileHandle(name,{create:true}),w=await h.createWritable();await w.write(value);await w.close()}
async function project(action){
 try{const dir=await pick();if(action==='new'){
   const state=get(),name=prompt('Project name','Untitled local project');if(!name?.trim())return;
   const manifest={schema_version:1,project_id:crypto.randomUUID(),project_name:name.trim(),assets:[]};
   for(const d of ['sources','generated','revisions','previews','metadata','reports','exports'])await dir.getDirectoryHandle(d,{create:true});
   await write(dir,'gandiwa-project.json',JSON.stringify(manifest,null,2)+'\n');await rememberDir(dir);put({projectName:manifest.project_name,manifest,master:null});
 } else {const {manifest}=await readManifest(dir);await rememberDir(dir);put({projectName:manifest.project_name,manifest,master:get().master||null});}
 document.querySelectorAll('#project-name').forEach(n=>n.textContent=get().projectName||'Untitled local project');
 }catch(e){document.querySelectorAll('[role=status]').forEach(n=>{if(!n.textContent.trim())n.textContent=e.message||'Project action failed.'})}
}
function projectButtons(){by('new-project')&&(by('new-project').onclick=()=>project('new'));by('open-project')&&(by('open-project').onclick=()=>project('open'));by('open-last-project')&&(by('open-last-project').onclick=async()=>{try{const dir=await recalledDir();if(!dir)throw Error('No remembered project folder. Use Open project.');const perm=await dir.requestPermission({mode:'read'});if(perm!=='granted')throw Error('Read permission was not granted for the remembered project folder.');const {manifest}=await readManifest(dir);put({projectName:manifest.project_name,manifest});document.querySelectorAll('#project-name').forEach(n=>n.textContent=manifest.project_name)}catch(e){alert(e.message||'Unable to reopen project.')}});document.querySelectorAll('#project-name').forEach(n=>{if(get().projectName)n.textContent=get().projectName});}
function ratio(){return {width:4096,height:3072,ratio:'4:3'}}
async function dispatch(promptText,contentType,model){const s=get();if(!s.projectName)throw Error('Open or create a local project first.');if(!confirm('Approve this prompt and create one billable image-generation job?'))throw Error('Generation cancelled before a job was created.');
 const target=ratio(), sid=crypto.randomUUID(), p={prompt_text:promptText,negative_prompt_text:'logo, watermark, brand name, random text, fake interface, malformed anatomy',content_type:contentType,creation_method:'generative_ai',provider_id:'fal',model_id:model,target_width:target.width,target_height:target.height,aspect_ratio:target.ratio,orientation:'landscape',stock_constraints:{no_logo:true,no_brand:true,no_watermark:true,no_random_text:true,no_fake_ui:true,no_unintentional_crop:true,no_malformed_anatomy:true,no_copyrighted_property:true,negative_space_decision:'none required'}};
 const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(p)));const hex=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');
 const payload={session:{topic:s.projectName,prompt:p,human_prompt_approval:true,approved_prompt_digest:hex,creative_approvals:[{stage:'prompt',human:'Master Peng',approved_at:new Date().toISOString(),prompt_digest:hex}],revisions:[]},rules_snapshot:{id:'adobe-stock-2026-09-08-v1',version:'adobe-stock-2026-09-08-v1'},idempotency_key:`creative-${sid}-${hex.slice(0,32)}`};
 await boot();const token=await csrf();const r=await fetch(`${API}/creative/jobs`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify(payload)}),job=await text(r);if(!r.ok)throw Error(job.detail||'Job could not be queued.');put({activeJob:job,activePrompt:promptText,contentType,model});return job;}
async function poll(job){const r=await fetch(`${API}/creative/jobs/${encodeURIComponent(job.id)}`,{credentials:'same-origin'}),b=await text(r);if(!r.ok)throw Error(b.detail||'Job status unavailable.');return b}
function create(){const form=by('generation-form');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const prompt=by('prompt').value.trim(),status=by('generation-status');if(!prompt){say('prompt-error','Add a prompt before generating an image.');return}if(by('provider').value!=='fal'){status.textContent='OpenAI connector is not available in backend yet. Choose fal.ai.';return}try{by('generate').disabled=true;status.textContent='Waiting for explicit approval…';const job=await dispatch(prompt,[...document.querySelectorAll('input[name=type]')].find(x=>x.checked)?.parentElement.textContent.trim().toLowerCase()||'photo',by('model').value);status.textContent=`Job ${job.id} queued. Polling backend status.`;const cancel=document.createElement('button');cancel.type='button';cancel.className='quiet';cancel.textContent='Request cancellation';cancel.onclick=async()=>{const token=await csrf();await fetch(`${API}/creative/jobs/${job.id}`,{method:'DELETE',credentials:'same-origin',headers:{'X-CSRF-Token':token}});cancel.disabled=true;status.textContent='Cancellation requested. Worker decides safe final status.'};by('generation-status').parentElement.append(cancel);const timer=setInterval(async()=>{try{const now=await poll(job);status.textContent=`Job ${now.id}: ${now.status}${now.queue_position?`, queue position ${now.queue_position}`:''}`;if(['succeeded','failed','cancelled','needs_review'].includes(now.status)){clearInterval(timer);put({activeJob:now});by('generate').disabled=false;if(now.status==='succeeded'&&now.artifact){by('generated-stage').className='stage-empty';by('generated-stage').textContent='Artifact ready in backend. Download from the job after opening the project workflow.';by('lock-master').disabled=false}else status.textContent+=now.message?`: ${now.message}`:''}}catch(err){clearInterval(timer);status.textContent=err.message;by('generate').disabled=false}},1200)}catch(err){status.textContent=err.message;by('generate').disabled=false}};
 by('lock-master').onclick=()=>{const s=get();if(!s.activeJob?.artifact)return say('generation-status','A succeeded job artifact is required before locking a master.');put({master:{jobId:s.activeJob.id,artifact:s.activeJob.artifact,prompt:s.activePrompt}});by('lock-master').textContent='Master locked';by('lock-master').disabled=true;by('go-prepare').hidden=false;say('generation-status','Master locked locally. Continue to Prepare.');};}
async function artifact(){const s=get();if(!s.master?.artifact)throw Error('No locked master artifact.');const r=await fetch(`${API}/artifacts/${encodeURIComponent(s.master.artifact.id)}/download`,{credentials:'same-origin'});if(!r.ok)throw Error('Artifact download unavailable or expired.');return new Blob([await r.arrayBuffer()],{type:s.master.artifact.media_type||'image/png'})}
async function preflightArtifact(blob, contentType){const vector=blob.type==='image/svg+xml';const endpoint=vector?SVG_PREFLIGHT_URL:RASTER_PREFLIGHT_URL;const query=vector?`?content_type=${encodeURIComponent(contentType==='photo'?'illustration':contentType)}`:`?content_type=${encodeURIComponent(contentType==='vector'?'illustration':contentType)}`;const r=await fetch(endpoint+query,{method:'POST',headers:{'Content-Type':blob.type||'application/octet-stream','X-Upload-Filename':vector?'master.svg':'master.png'},body:blob});const report=await text(r);if(!r.ok)throw Error(report.detail||'Preflight failed.');return report}
function prepare(){if(!by('master-stage'))return;const s=get();if(!s.master){say('audit-status','No locked master. Return to Create and lock a succeeded artifact.');return}by('master-stage').textContent='Locked master artifact';by('audit-loading').hidden=true;by('audit-checks').hidden=false;say('audit-status','Master lock loaded. Run preflight before download.');
 const title=by('generate-title');if(title)title.onclick=()=>say('metadata-status','Metadata assistant needs a configured 9Router model. This rev3 page does not fabricate suggestions.');const check=by('metadata-reviewed');if(check)check.onchange=()=>by('download-ready').disabled=!check.checked;const download=by('download-ready');if(download)download.onclick=async()=>{try{const blob=await artifact();say('download-feedback','Running byte-level preflight before download…');const report=await preflightArtifact(blob,get().contentType||'photo');if(report.eligible_for_submission!==true)throw Error(`Preflight blocked download: ${report.verdict||'unknown verdict'}.`);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gandiwa-master';a.click();URL.revokeObjectURL(url);say('download-feedback','Artifact passed preflight and downloaded from the owner-scoped backend route.',true)}catch(e){say('download-feedback',e.message)}}}
function metadata(){if(!by('save-metadata'))return;const locked=()=>!!get().master;const render=()=>{const yes=locked();by('master-state').textContent=yes?'MASTER LOCKED':'MASTER NOT LOCKED';by('lock-master').textContent=yes?'Master locked':'Lock master in Create first';['generate-title','generate-keywords','generate-metadata'].forEach(id=>by(id).disabled=!yes)};by('lock-master').onclick=()=>say('save-feedback','Lock the actual succeeded image from Create first.');by('save-metadata').onclick=async()=>{if(!locked())return say('save-feedback','Lock a master first.');const body={title:by('title-output').value,keywords:by('keywords-output').value,description:by('description-input').value,master:get().master,updatedAt:new Date().toISOString()};try{const dir=await pick();await write(await dir.getDirectoryHandle('metadata',{create:true}),'master-metadata.json',JSON.stringify(body,null,2));say('save-feedback','Reviewed metadata saved in the browser-owned project folder.',true)}catch(e){say('save-feedback',e.message)}};render()}
function revisions(){const form=by('revision-form');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const reason=by('revision-reason').value.trim();if(!reason)return say('revision-error','Describe the meaningful change before creating a billed revision.');put({revisionReason:reason});location.href='index.html'},true)}
function preflight(){/* Master artifact preflight is invoked after artifact download only; no fake byte inspection. */}
function init(){projectButtons();create();prepare();metadata();revisions();preflight()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
