(() => {
'use strict';
const API='/api/v1'; const KEY='gandiwa-rev3-create-state-v1'; const $=s=>document.querySelector(s);
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const say=(id,message,kind='')=>{const n=$(id);n.className=`status-line ${kind}`;n.innerHTML=`<i class="status-dot ${kind}"></i><span>${message}</span>`};
const bodyJson=async r=>{const t=await r.text();try{return t?JSON.parse(t):{}}catch{return{detail:t}}};
async function csrf(){const r=await fetch(`${API}/auth/csrf`,{credentials:'same-origin'}),b=await bodyJson(r);if(!r.ok||!b.csrf_token)throw Error('Security token could not be prepared.');return b.csrf_token}
async function bytes(){const master=get().master;if(!master?.artifact?.id)throw Error('Lock a completed backend artifact in Create first.');const r=await fetch(`${API}/artifacts/${encodeURIComponent(master.artifact.id)}/download`,{credentials:'same-origin'});if(!r.ok)throw Error('The locked artifact is unavailable or has expired. Return to Create and generate again.');return {master,blob:await r.blob()}}
function findings(report){const list=$('#audit-checks');list.innerHTML='';for(const f of report.findings||[]){const a=document.createElement('article');a.className='check';a.innerHTML=`<i>${report.verdict==='fail'?'!':'✓'}</i><div><strong>${f.rule_id||'Preflight finding'}</strong><p>${f.message||''}</p></div>`;list.append(a)}if(!list.children.length)list.innerHTML='<article class="check"><i>✓</i><div><strong>Technical report complete</strong><p>No additional preflight findings were returned.</p></div></article>';list.hidden=false}
async function preflight(){const {master,blob}=await bytes();if(master.contentType==='vector')throw Error('Vector master preflight needs the SVG workflow, which is not connected to the image-generation queue.');const token=await csrf();const ext=blob.type==='image/jpeg'?'jpg':'png';const r=await fetch(`${API}/raster/preflight?content_type=${encodeURIComponent(master.contentType||'photo')}`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':blob.type||'image/png','X-CSRF-Token':token,'X-Upload-Filename':`locked-master.${ext}`},body:blob}),report=await bodyJson(r);if(!r.ok||typeof report.eligible_for_submission!=='boolean')throw Error('Raster preflight did not return a valid technical report.');return {master,blob,report}}
async function inspect(){const loading=$('#audit-loading');loading.hidden=false;say('#audit-status','Reading owner-scoped artifact bytes for internal preflight.','loading');try{const result=await preflight();window.__gandiwaPrepare=result;findings(result.report);const r=result.report;$('#master-label').textContent=`${r.width||'?'} × ${r.height||'?'} · ${r.megapixels||'?'} MP`;$('#master-stage').textContent=`Locked master artifact · ${r.detected_mime_type||'unknown type'} · ${r.width||'?'} × ${r.height||'?'}`;$('#master-stage').dataset.ready='true';const kind=r.eligible_for_submission?'ready':'error';say('#audit-status',`Internal preflight: ${r.verdict}. ${r.eligible_for_submission?'Technical gate passed. Human metadata review is still required.':'Resolve the listed technical findings before export.'}`,kind);$('#metadata-reviewed').onchange=syncDownload;return result}catch(e){say('#audit-status',e.message,'error');throw e}finally{loading.hidden=true}}
function syncDownload(){const r=window.__gandiwaPrepare?.report;$('#download-ready').disabled=!(r?.eligible_for_submission&&$('#metadata-reviewed').checked)}
async function download(){const current=window.__gandiwaPrepare||await preflight();if(!current.report.eligible_for_submission||!$('#metadata-reviewed').checked)throw Error('Run a passing preflight and confirm human metadata review before download.');const url=URL.createObjectURL(current.blob);const a=document.createElement('a');a.href=url;a.download=`${get().projectName||'gandiwa-master'}.${current.blob.type==='image/jpeg'?'jpg':'png'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);$('#download-feedback').textContent='Owner-scoped artifact download started. Save the metadata separately in your local project.'}
async function metadata(){
 const cfg=(()=>{try{return JSON.parse(localStorage.getItem('gandiwa-rev3-assistant')||'{}')}catch{return{}}})();
 const master=get().master;
 if(!master?.artifact){say('#metadata-status','Lock a completed master before requesting metadata.','error');return}
 if(!cfg.instance_id||!cfg.model_id){say('#metadata-status','Choose an explicit 9Router instance and model in Settings before requesting metadata. No suggestion was generated.','error');return}
 say('#metadata-status','Requesting one schema-validated metadata suggestion. Human review remains required.','loading');
 try{
  await fetch(`${API}/creative/bootstrap`,{credentials:'same-origin'});
  const token=await csrf();
  const r=await fetch(`${API}/creative/assistant/metadata`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify({instance_id:cfg.instance_id,model_id:cfg.model_id,topic:master.prompt||get().projectName||'Locked master image',content_type:master.contentType||'photo'})}),b=await bodyJson(r);
  if(!r.ok||typeof b.title!=='string'||!Array.isArray(b.keywords))throw Error(b.detail||'Metadata assistant returned an invalid response.');
  $('#title-output').value=b.title;$('#keywords-output').value=b.keywords.join(', ');$('#description-output').value='Review the title and keywords against the locked master before writing a description.';
  say('#metadata-status',`Metadata suggestion returned by ${b.model_id||cfg.model_id}. Review and edit every field.`, 'ready');
 }catch(e){say('#metadata-status',e.message||'Metadata request failed. No suggestion was applied.','error')}
}
function theme(){const night=!document.documentElement.classList.contains('night');document.documentElement.classList.toggle('night',night);$('#night-mode').setAttribute('aria-pressed',String(night));}
function init(){$('#night-mode').onclick=theme;const s=get();$('#project-name').textContent=s.projectName||'Untitled local project';for(const id of ['#generate-title','#generate-keywords','#generate-metadata'])$(id).onclick=metadata;$('#download-ready').onclick=()=>download().catch(e=>$('#download-feedback').textContent=e.message);if(!s.master?.artifact){say('#audit-status','Lock a completed image in Create before this page can inspect it.','error');return}inspect().then(()=>syncDownload()).catch(()=>{});}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
