(() => {
'use strict';
const API='/api/v1'; const STATE_KEY='gandiwa-rev3-create-state-v1'; const DB='gandiwa-rev3-project-handles';
const $=s=>document.querySelector(s); const state=()=>{try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{return{}}};
const save=x=>localStorage.setItem(STATE_KEY,JSON.stringify({...state(),...x}));
const setStatus=(msg,kind='')=>{const n=$('#generation-status');n.className=`status-line ${kind}`;n.innerHTML=`<i class="status-dot ${kind}" aria-hidden="true"></i><span>${msg}</span>`};
const json=async r=>{const raw=await r.text();try{return raw?JSON.parse(raw):{}}catch{return{detail:raw}}};
function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('directories');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error('Browser project storage is unavailable.'))})}
async function remember(directory){const db=await database();try{await new Promise((resolve,reject)=>{const r=db.transaction('directories','readwrite').objectStore('directories').put(directory,'active');r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}finally{db.close()}}
async function remembered(){const db=await database();try{return await new Promise((resolve,reject)=>{const r=db.transaction('directories','readonly').objectStore('directories').get('active');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}finally{db.close()}}
async function pickDirectory(){if(!window.showDirectoryPicker)throw Error('Use Chrome or Edge for browser-owned local project folders.');try{return await window.showDirectoryPicker()}catch(e){if(e&&e.name==='AbortError')return null;throw e}}
async function write(directory,name,value){const h=await directory.getFileHandle(name,{create:true});const w=await h.createWritable();await w.write(value);await w.close()}
async function readProject(directory){const h=await directory.getFileHandle('gandiwa-project.json',{create:false});const raw=await (await h.getFile()).text();return {raw,manifest:JSON.parse(raw)}}
async function createProject(){const name=prompt('Project name','Untitled local project');if(!name?.trim())return;if(window.__rev3WatchTimer){clearInterval(window.__rev3WatchTimer);window.__rev3WatchTimer=null;const cancel=$('#cancel-job');if(cancel)cancel.remove()}const directory=await pickDirectory();if(!directory){setStatus('Folder picker cancelled. No project created.');return}const manifest={schema_version:1,project_id:crypto.randomUUID(),project_name:name.trim(),assets:[]};for(const d of ['sources','generated','revisions','previews','metadata','reports','exports'])await directory.getDirectoryHandle(d,{create:true});await write(directory,'gandiwa-project.json',JSON.stringify(manifest,null,2)+'\n');await remember(directory);save({projectName:manifest.project_name,manifest});$('#project-name').textContent=manifest.project_name;setStatus('Local project created. Review a prompt before generating.','ready')}
async function openProject(directory=undefined){if(window.__rev3WatchTimer){clearInterval(window.__rev3WatchTimer);window.__rev3WatchTimer=null;const cancel=$('#cancel-job');if(cancel)cancel.remove()}const selected=directory||await pickDirectory();if(!selected){setStatus('Folder picker cancelled. No project opened.');return}const permission=await selected.requestPermission({mode:'read'});if(permission!=='granted')throw Error('Read permission was not granted for this project folder.');let manifest;try{({manifest}=await readProject(selected))}catch(e){throw Error('This folder has no gandiwa-project.json, so it is not a Gandiwa project folder. Pick the folder you created with "New project" (it contains sources/, generated/, reports/, and gandiwa-project.json).')}await remember(selected);save({projectName:manifest.project_name,manifest});$('#project-name').textContent=manifest.project_name;setStatus('Local project opened.','ready')}
async function csrf(){const r=await fetch(`${API}/auth/csrf`,{credentials:'same-origin'}),b=await json(r);if(!r.ok||!b.csrf_token)throw Error('Security token could not be prepared.');return b.csrf_token}
async function bootstrap(){const r=await fetch(`${API}/creative/bootstrap`,{credentials:'same-origin'});if(!r.ok)throw Error('Creative backend session is unavailable.')}
function selectedType(){return document.querySelector('input[name=type]:checked')?.value||'photo'}
function syncProvider(){const fal=$('#provider').value==='fal';$('#model').innerHTML=fal?'<option value="fal-ai/flux/schnell">fal-ai/flux/schnell</option>':'<option value="gpt-image-2.5-sunburst">gpt-image-2.5-sunburst</option>';$('#provider-summary').textContent=`${$('#provider').selectedOptions[0].text} · ${$('#model').value}`}
async function digest(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function enqueue(){const prompt=$('#prompt').value.trim();if(!prompt){$('#prompt-error').textContent='Add a prompt before generating an image.';$('#prompt').focus();return}$('#prompt-error').textContent='';const provider=$('#provider').value;const current=state();if(!current.projectName){setStatus('Create or open a local project before generation.','error');return}const type=selectedType();if(type==='vector'){setStatus(`${provider} raster generation cannot create a Vector master. Choose Photo or Illustration.`,'error');return}const isOpenAI=provider==='openai';const width=isOpenAI?2048:4096,height=isOpenAI?2048:3072,ratio=isOpenAI?'1:1':'4:3';const exact=`${width}×${height}, ${$('#model').value}, quality auto, PNG, background auto`;if(!confirm(`Approve one ${provider} generation job with exact parameters: ${exact}? This can use provider credit and cannot be silently retried.`)){setStatus('No job was created. Prompt approval was cancelled.');return}
const promptSpec={prompt_text:prompt,negative_prompt_text:'logo, watermark, brand name, random text, fake interface, malformed anatomy',content_type:type,creation_method:'generative_ai',provider_id:provider,model_id:$('#model').value,target_width:width,target_height:height,aspect_ratio:ratio,orientation:isOpenAI?'square':'landscape',generation_operation:'generate',source_artifact_id:null,quality:'auto',output_format:'png',background:'auto',stock_constraints:{no_logo:true,no_brand:true,no_watermark:true,no_random_text:true,no_fake_ui:true,no_unintentional_crop:true,no_malformed_anatomy:true,no_copyrighted_property:true,negative_space_decision:'none required'}};const approved=await Rev3Canonical.approvalDigest(promptSpec);const sessionId=crypto.randomUUID();const payload={session:{topic:current.projectName,prompt:promptSpec,human_prompt_approval:true,approved_prompt_digest:approved,creative_approvals:[{stage:'prompt',human:'Master Peng',approved_at:new Date().toISOString(),prompt_digest:approved}],revisions:[]},rules_snapshot:{id:'adobe-stock-2026-09-08-v1',version:'adobe-stock-2026-09-08-v1'},idempotency_key:`creative-${sessionId}-${approved.slice(0,32)}`};$('#generate').disabled=true;$('#generation-loading').hidden=false;setStatus('Creating one approved queue job…','loading');const history=(current.jobHistory||[]).filter(x=>x.id);try{await bootstrap();const token=await csrf();const r=await fetch(`${API}/creative/jobs`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify(payload)}),job=await json(r);if(!r.ok)throw Error(job.detail||'Queue rejected this generation job.');save({activeJob:job,activePrompt:prompt,contentType:type,model:promptSpec.model_id,jobHistory:[{id:job.id,status:job.status,artifact:job.artifact||null,prompt,contentType:type,provider:promptSpec.provider_id,model:promptSpec.model_id,rulesSnapshot:'adobe-stock-2026-09-08-v1',approvedDigest:approved,num_images:1},...history].slice(0,50)});watch(job)}catch(error){$('#generate').disabled=false;$('#generation-loading').hidden=true;setStatus(error.message||'Generation job could not be created.','error')}}
async function requestCancel(job){const token=await csrf();const r=await fetch(`${API}/creative/jobs/${encodeURIComponent(job.id)}`,{method:'DELETE',credentials:'same-origin',headers:{'X-CSRF-Token':token}}),b=await json(r);if(!r.ok)throw Error(b.detail||'Cancellation request failed.');return b}
function watch(job){
 // Issue #26 AC: queue position/stage/cancel/needs-review/artifact expiry are shown.
 if(window.__rev3WatchTimer){clearInterval(window.__rev3WatchTimer)}
 window.__rev3WatchTimer=null;
 window.__rev3WatchJobId=job.id;
 const STAGE_LABEL={queued:'Queued',dispatched:'Dispatched',running:'Running',waiting_provider:'Waiting for provider',needs_review:'Needs review',failed:'Failed',cancelled:'Cancelled',succeeded:'Succeeded'};
 const cancel=$('#cancel-job')||Object.assign(document.createElement('button'),{id:'cancel-job',type:'button',className:'quiet',textContent:'Request cancellation'});
 if(!cancel.isConnected)$('#generation-status').parentElement.append(cancel);
 cancel.onclick=async()=>{try{cancel.disabled=true;await requestCancel(job);setStatus('Cancellation requested. The worker decides the safe final outcome.','loading')}catch(e){cancel.disabled=false;setStatus(e.message,'error')}};
 const timer=setInterval(async()=>{
 if(window.__rev3WatchTimer&&window.__rev3WatchTimer!==timer)clearInterval(window.__rev3WatchTimer);
 try{
   const r=await fetch(`${API}/creative/jobs/${encodeURIComponent(job.id)}`,{credentials:'same-origin'}),now=await json(r);
   if(!r.ok)throw Error(now.detail||'Job status unavailable.');
   const stage=STAGE_LABEL[now.status]||now.status;
   const q=now.status==='queued'&&now.queue_position?`, queue position ${now.queue_position}`:'';
   const expiry=now.artifact_expires_at?`, artifact expires at ${new Date(now.artifact_expires_at).toLocaleString()}`:'';
   setStatus(`Job ${now.id}: ${stage}${q}${expiry}.`,'loading');
   if(['queued','dispatched','running','waiting_provider'].includes(now.status)){/* keep polling */}
   else if(['succeeded','failed','cancelled','needs_review'].includes(now.status)){
    clearInterval(timer);$('#generation-loading').hidden=true;$('#generate').disabled=false;cancel.remove();
    if(now.status==='succeeded'&&now.artifact){
     $('#generated-stage').className='stage-empty';$('#generated-stage').dataset.ready='true';$('#generated-stage').textContent='Artifact is ready in the owner-scoped backend. Lock it as master to continue.';$('#lock-master').disabled=false;setStatus(`Artifact ready, expires at ${new Date(now.artifact_expires_at).toLocaleString()}. Lock this image as master to continue.`,'ready');save({activeJob:now});
    }else if(now.status==='needs_review'){
     setStatus(`Needs review: the dispatch ended without a trustworthy outcome. Redacted code: ${now.error_code||'UNKNOWN'}. Review the job in the queue before retrying; do not resubmit blindly.`,'error');
    }else setStatus(`${stage}: ${now.message||'No artifact was created.'}`,now.status==='cancelled'?'':'error');
   }
  }catch(e){clearInterval(timer);$('#generation-loading').hidden=true;$('#generate').disabled=false;setStatus(e.message||'Job monitor stopped. The backend job remains authoritative.','error')}
 },1200);
 window.__rev3WatchTimer=timer;
 }
function appendRevision(entry){
 // Paku 6: one stable ledger entry per locked job; re-locking the same job
 // must never fork history into two entries.
 const s=state();const ledger=s.revisionLedger||[];
 if(ledger.some(x=>x.jobId===entry.jobId))return ledger.length;
 ledger.unshift({jobId:entry.jobId,artifact:entry.artifact||null,prompt:entry.prompt||'',contentType:entry.contentType||'',approvedDigest:entry.approvedDigest||s.activeJob?.approvedDigest||null,lockedAt:new Date().toISOString()});
 save({revisionLedger:ledger.slice(0,50)});
 return ledger.length;
}
function lockMaster(){const s=state();if(!s.activeJob?.artifact){setStatus('A succeeded backend artifact is required before a master can be locked.','error');return}const n=appendRevision({jobId:s.activeJob.id,artifact:s.activeJob.artifact,prompt:s.activePrompt,contentType:s.contentType,approvedDigest:s.activeJob.approvedDigest||null});save({master:{jobId:s.activeJob.id,artifact:s.activeJob.artifact,prompt:s.activePrompt,contentType:s.contentType}});$('#lock-master').disabled=true;$('#lock-master').textContent='Master locked';$('#go-prepare').hidden=false;setStatus(`Master locked as revision ${String(n).padStart(2,'0')} in local browser state. Continue to Prepare.`,'ready')}
function theme(){const next=!document.documentElement.classList.contains('night');document.documentElement.classList.toggle('night',next);$('#night-mode').setAttribute('aria-pressed',String(next));$('#night-mode').setAttribute('aria-label',next?'Enable day mode':'Enable night mode');$('#night-mode').title=next?'Day mode':'Night mode';localStorage.setItem('gandiwa-rev3-theme',next?'night':'day')}
function init(){if(localStorage.getItem('gandiwa-rev3-theme')==='night')theme();$('#night-mode').onclick=theme;$('#provider').onchange=syncProvider;$('#model').onchange=syncProvider;syncProvider();$('#new-project').onclick=()=>createProject().catch(e=>setStatus(e.message,'error'));$('#open-project').onclick=()=>openProject().catch(e=>setStatus(e.message,'error'));$('#open-last-project').onclick=async()=>{try{const dir=await remembered();if(!dir)throw Error('No remembered project. Use Open project.');await openProject(dir)}catch(e){setStatus(e.message,'error')}};$('#generation-form').onsubmit=e=>{e.preventDefault();enqueue().catch(err=>setStatus(err.message,'error'))};$('#regenerate').onclick=()=>{$('#prompt').focus();setStatus('Change the prompt meaningfully, then approve a new billed job.');};$('#lock-master').onclick=lockMaster;const s=state();if(s.projectName)$('#project-name').textContent=s.projectName;if(s.activeJob&&['queued','running'].includes(s.activeJob.status))watch(s.activeJob);if(s.master){$('#lock-master').disabled=true;$('#lock-master').textContent='Master locked';$('#go-prepare').hidden=false}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
