"""Durable temporary artifact storage boundary for Issue #22."""

from __future__ import annotations

import hashlib
import os
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from sqlalchemy import Engine, text


class ArtifactError(RuntimeError):
    """Base artifact lifecycle failure."""


class AccessDenied(ArtifactError):
    """Artifact exists but is not owned by the current session."""


class ExpiredArtifact(ArtifactError):
    """Artifact is no longer available for retrieval."""


@dataclass(frozen=True, slots=True)
class TemporaryArtifact:
    id: str
    job_id: str
    owner_session_id: str
    storage_name: str
    download_name: str
    media_type: str
    size_bytes: int
    sha256: str
    created_at: datetime
    expires_at: datetime
    retrieved_at: datetime | None


def _now() -> datetime:
    return datetime.now(UTC)


def _dbtime(value: datetime) -> str:
    return value.isoformat(timespec="microseconds")


def _parse_time(value: Any) -> datetime | None:
    if value is None or isinstance(value, datetime):
        return value
    return datetime.fromisoformat(str(value))


def _record(row: Any) -> TemporaryArtifact:
    item = row._mapping
    created = _parse_time(item["created_at"])
    expires = _parse_time(item["expires_at"])
    if created is None or expires is None:
        raise ArtifactError("artifact timestamps are missing")
    return TemporaryArtifact(
        id=str(item["id"]),
        job_id=str(item["job_id"]),
        owner_session_id=str(item["owner_session_id"]),
        storage_name=str(item["storage_name"]),
        download_name=str(item["download_name"]),
        media_type=str(item["media_type"]),
        size_bytes=int(item["size_bytes"]),
        sha256=str(item["sha256"]),
        created_at=created,
        expires_at=expires,
        retrieved_at=_parse_time(item["retrieved_at"]),
    )


class ArtifactStore:
    """Keeps generated bytes private until their owner retrieves them."""

    AccessDenied = AccessDenied
    ExpiredArtifact = ExpiredArtifact

    def __init__(self, engine: Engine, artifact_dir: Path) -> None:
        self.engine = engine
        self.artifact_dir = artifact_dir.resolve()

    def stage_bytes(
        self,
        *,
        job_id: str,
        owner_session_id: str,
        download_name: str,
        media_type: str,
        payload: bytes,
        ttl_seconds: int,
    ) -> TemporaryArtifact:
        if not job_id or not owner_session_id or not download_name or not media_type:
            raise ArtifactError("artifact identity and media type are required")
        if ttl_seconds < 1:
            raise ArtifactError("artifact ttl must be positive")
        self.artifact_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
        artifact_id = str(uuid.uuid4())
        storage_name = f"{artifact_id}.bin"
        target = self.private_path_from_name(storage_name)
        temporary = self.private_path_from_name(f".{artifact_id}.staging")
        created_at = _now()
        expires_at = created_at + timedelta(seconds=ttl_seconds)
        digest = hashlib.sha256(payload).hexdigest()
        try:
            with open(temporary, "xb") as handle:
                os.chmod(temporary, 0o600)
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            with self.engine.begin() as connection:
                connection.execute(
                    text(
                        "INSERT INTO temporary_artifact "
                        "(id, job_id, owner_session_id, storage_name, download_name, media_type, "
                        "size_bytes, sha256, created_at, expires_at) VALUES "
                        "(:id, :job_id, :owner, :storage, :download, :media_type, "
                        ":size, :sha256, :created, :expires)"
                    ),
                    {
                        "id": artifact_id,
                        "job_id": job_id,
                        "owner": owner_session_id,
                        "storage": storage_name,
                        "download": download_name,
                        "media_type": media_type,
                        "size": len(payload),
                        "sha256": digest,
                        "created": _dbtime(created_at),
                        "expires": _dbtime(expires_at),
                    },
                )
            os.replace(temporary, target)
        except Exception:
            temporary.unlink(missing_ok=True)
            target.unlink(missing_ok=True)
            raise
        return self.get_for_owner(artifact_id, owner_session_id)

    def private_path_from_name(self, storage_name: str) -> Path:
        path = (self.artifact_dir / storage_name).resolve()
        if not path.is_relative_to(self.artifact_dir):
            raise ArtifactError("artifact storage escaped private directory")
        return path

    def private_path(self, artifact: TemporaryArtifact) -> Path:
        return self.private_path_from_name(artifact.storage_name)

    def verify_integrity(self, artifact: TemporaryArtifact) -> bool:
        path = self.private_path(artifact)
        if not path.is_file() or path.stat().st_size != artifact.size_bytes:
            return False
        digest = hashlib.sha256()
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest() == artifact.sha256

    def get_for_owner(self, artifact_id: str, owner_session_id: str) -> TemporaryArtifact:
        with self.engine.connect() as connection:
            row = connection.execute(
                text("SELECT * FROM temporary_artifact WHERE id = :id"), {"id": artifact_id}
            ).fetchone()
        if row is None:
            raise AccessDenied("artifact is unavailable")
        artifact = _record(row)
        if artifact.owner_session_id != owner_session_id:
            raise AccessDenied("artifact is unavailable")
        if artifact.expires_at <= _now():
            raise ExpiredArtifact("artifact has expired")
        return artifact

    def claim_retrieval(
        self,
        artifact_id: str,
        owner_session_id: str,
        *,
        lease_seconds: int,
    ) -> TemporaryArtifact:
        if lease_seconds < 1:
            raise ArtifactError("retrieval lease must be positive")
        now = _now()
        with self.engine.begin() as connection:
            result = connection.execute(
                text(
                    "UPDATE temporary_artifact SET retrieval_lease_expires_at = :lease "
                    "WHERE id = :id AND owner_session_id = :owner AND expires_at > :now "
                    "AND (retrieval_lease_expires_at IS NULL OR retrieval_lease_expires_at <= :now)"
                ),
                {
                    "lease": _dbtime(now + timedelta(seconds=lease_seconds)),
                    "id": artifact_id,
                    "owner": owner_session_id,
                    "now": _dbtime(now),
                },
            )
            if result.rowcount != 1:
                raise AccessDenied("artifact is unavailable")
        return self.get_for_owner(artifact_id, owner_session_id)

    def complete_retrieval(self, artifact_id: str, owner_session_id: str) -> None:
        """Release the stream lease after a completed response; bytes remain until TTL."""
        with self.engine.begin() as connection:
            result = connection.execute(
                text(
                    "UPDATE temporary_artifact SET retrieved_at = :now, "
                    "retrieval_lease_expires_at = NULL WHERE id = :id "
                    "AND owner_session_id = :owner"
                ),
                {"now": _dbtime(_now()), "id": artifact_id, "owner": owner_session_id},
            )
            if result.rowcount != 1:
                raise AccessDenied("artifact is unavailable")

    def cleanup_expired(self) -> int:
        """Delete only expired records that have no active retrieval lease."""
        now = _dbtime(_now())
        with self.engine.begin() as connection:
            rows = connection.execute(
                text(
                    "SELECT * FROM temporary_artifact WHERE expires_at <= :now "
                    "AND (retrieval_lease_expires_at IS NULL OR retrieval_lease_expires_at <= :now)"
                ),
                {"now": now},
            ).fetchall()
            claimed: list[TemporaryArtifact] = []
            for row in rows:
                artifact = _record(row)
                deleted = connection.execute(
                    text(
                        "DELETE FROM temporary_artifact WHERE id = :id AND expires_at <= :now "
                        "AND (retrieval_lease_expires_at IS NULL "
                        "OR retrieval_lease_expires_at <= :now)"
                    ),
                    {"id": artifact.id, "now": now},
                )
                if deleted.rowcount == 1:
                    claimed.append(artifact)
        for artifact in claimed:
            self.private_path(artifact).unlink(missing_ok=True)
        return len(claimed)
